from typing import Optional, Dict

class AIHandler:
    config: Dict[str, str]
    def __init__(self) -> None: ...
    def _load_config(self) -> Dict[str, str]: ...
    def generate_filename(self, text: str) -> Optional[str]: ... 